# Theme metadata
name = "Basic"
license = "MIT"
licenselink = "https://github.com/yourname/Basic/blob/main/LICENSE"
description = "A minimal, monochrome Hugo theme focused on simplicity and readability."
homepage = "https://github.com/yourname/Basic"
tags = ["blog", "minimal", "monochrome", "simple", "responsive"]
features = ["responsive", "clean", "minimal", "monochrome"]
min_version = "0.74.0"

[author]
  name = "Your Name"
  homepage = "https://yoursite.com" 