baseURL = 'https://kamikigit.github.io/'
languageCode = 'ja-jp'
title = 'kamiki.github.io'
theme = 'Basic'
DefaultContentLanguage = 'ja'
buildDrafts = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = 'category'
  subcategory = 'subcategory'
  tag = 'tags'
  series = 'series'

# [languages]
#   [languages.ja]
#     languageName = '日本語'
#     weight = 1
#     title = 'kamiki.github.io'
#   [languages.en]
#     languageName = 'English'
#     weight = 2
#     title = 'kamiki.github.io'

[menu]
  [[menu.main]]
    name = "ホーム"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "ブログ"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "プロフィール"
    url = "/about/"
    weight = 3

# [languages.en.menu]
#   [[languages.en.menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1
#   [[languages.en.menu.main]]
#     name = "Blog"
#     url = "/posts/"
#     weight = 2
#   [[languages.en.menu.main]]
#     name = "Profile"
#     url = "/about/"
#     weight = 3
